package entity;
// Generated 3/04/2018 10:11:12 PM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Casouso generated by hbm2java
 */
@Entity
@Table(name="casouso"
    ,catalog="AdministracionProyectosSoftware"
)
public class Casouso  implements java.io.Serializable {


     private Integer id;
     private Proyecto proyecto;
     private String nombre;
     private String descripcion;
     private Set<CasousoPrecondiciones> casousoPrecondicioneses = new HashSet<CasousoPrecondiciones>(0);
     private Set<CasousoRequisitosEspeciales> casousoRequisitosEspecialeses = new HashSet<CasousoRequisitosEspeciales>(0);
     private Set<CasousoActor> casousoActors = new HashSet<CasousoActor>(0);
     private Set<CasousoPostcondiciones> casousoPostcondicioneses = new HashSet<CasousoPostcondiciones>(0);

    public Casouso() {
    }

	
    public Casouso(Proyecto proyecto, String nombre, String descripcion) {
        this.proyecto = proyecto;
        this.nombre = nombre;
        this.descripcion = descripcion;
    }
    public Casouso(Proyecto proyecto, String nombre, String descripcion, Set<CasousoPrecondiciones> casousoPrecondicioneses, Set<CasousoRequisitosEspeciales> casousoRequisitosEspecialeses, Set<CasousoActor> casousoActors, Set<CasousoPostcondiciones> casousoPostcondicioneses) {
       this.proyecto = proyecto;
       this.nombre = nombre;
       this.descripcion = descripcion;
       this.casousoPrecondicioneses = casousoPrecondicioneses;
       this.casousoRequisitosEspecialeses = casousoRequisitosEspecialeses;
       this.casousoActors = casousoActors;
       this.casousoPostcondicioneses = casousoPostcondicioneses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_proyecto", nullable=false)
    public Proyecto getProyecto() {
        return this.proyecto;
    }
    
    public void setProyecto(Proyecto proyecto) {
        this.proyecto = proyecto;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="casouso")
    public Set<CasousoPrecondiciones> getCasousoPrecondicioneses() {
        return this.casousoPrecondicioneses;
    }
    
    public void setCasousoPrecondicioneses(Set<CasousoPrecondiciones> casousoPrecondicioneses) {
        this.casousoPrecondicioneses = casousoPrecondicioneses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="casouso")
    public Set<CasousoRequisitosEspeciales> getCasousoRequisitosEspecialeses() {
        return this.casousoRequisitosEspecialeses;
    }
    
    public void setCasousoRequisitosEspecialeses(Set<CasousoRequisitosEspeciales> casousoRequisitosEspecialeses) {
        this.casousoRequisitosEspecialeses = casousoRequisitosEspecialeses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="casouso")
    public Set<CasousoActor> getCasousoActors() {
        return this.casousoActors;
    }
    
    public void setCasousoActors(Set<CasousoActor> casousoActors) {
        this.casousoActors = casousoActors;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="casouso")
    public Set<CasousoPostcondiciones> getCasousoPostcondicioneses() {
        return this.casousoPostcondicioneses;
    }
    
    public void setCasousoPostcondicioneses(Set<CasousoPostcondiciones> casousoPostcondicioneses) {
        this.casousoPostcondicioneses = casousoPostcondicioneses;
    }




}


