package entity;
// Generated 3/04/2018 10:11:12 PM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CasousoRequisitosEspeciales generated by hbm2java
 */
@Entity
@Table(name="casouso_requisitosEspeciales"
    ,catalog="AdministracionProyectosSoftware"
)
public class CasousoRequisitosEspeciales  implements java.io.Serializable {


     private Integer id;
     private Casouso casouso;
     private String requisitosEspeciales;

    public CasousoRequisitosEspeciales() {
    }

    public CasousoRequisitosEspeciales(Casouso casouso, String requisitosEspeciales) {
       this.casouso = casouso;
       this.requisitosEspeciales = requisitosEspeciales;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="id_casouso", nullable=false)
    public Casouso getCasouso() {
        return this.casouso;
    }
    
    public void setCasouso(Casouso casouso) {
        this.casouso = casouso;
    }

    
    @Column(name="requisitos_especiales", nullable=false, length=50)
    public String getRequisitosEspeciales() {
        return this.requisitosEspeciales;
    }
    
    public void setRequisitosEspeciales(String requisitosEspeciales) {
        this.requisitosEspeciales = requisitosEspeciales;
    }




}


