package entity;
// Generated 3/04/2018 10:11:12 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Proyecto generated by hbm2java
 */
@Entity
@Table(name="proyecto"
    ,catalog="AdministracionProyectosSoftware"
)
public class Proyecto  implements java.io.Serializable {


     private Integer id;
     private String nombre;
     private String cliente;
     private String descripcion;
     private Date fechaInicio;
     private Date fechaFin;
     private Set<Casouso> casousos = new HashSet<Casouso>(0);

    public Proyecto() {
    }

	
    public Proyecto(String nombre, String cliente, String descripcion) {
        this.nombre = nombre;
        this.cliente = cliente;
        this.descripcion = descripcion;
    }
    public Proyecto(String nombre, String cliente, String descripcion, Date fechaInicio, Date fechaFin, Set<Casouso> casousos) {
       this.nombre = nombre;
       this.cliente = cliente;
       this.descripcion = descripcion;
       this.fechaInicio = fechaInicio;
       this.fechaFin = fechaFin;
       this.casousos = casousos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="nombre", nullable=false, length=30)
    public String getNombre() {
        return this.nombre;
    }
    
    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    
    @Column(name="cliente", nullable=false, length=30)
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="descripcion", nullable=false, length=65535)
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_inicio", length=10)
    public Date getFechaInicio() {
        return this.fechaInicio;
    }
    
    public void setFechaInicio(Date fechaInicio) {
        this.fechaInicio = fechaInicio;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="fecha_fin", length=10)
    public Date getFechaFin() {
        return this.fechaFin;
    }
    
    public void setFechaFin(Date fechaFin) {
        this.fechaFin = fechaFin;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="proyecto")
    public Set<Casouso> getCasousos() {
        return this.casousos;
    }
    
    public void setCasousos(Set<Casouso> casousos) {
        this.casousos = casousos;
    }




}


